inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"

Bundler/OrderedGems:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true

Lint/UnneededCopDisableDirective:
  Exclude:
    - 'lib/tasks/heroku_clear_tasks.rake' # File loaded by heroku when running ci

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
