apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-url
  namespace: {{ .Values.common.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: database-url
  data:
  - secretKey: url
    remoteRef:
      key: kv/data/rdv-solidarites/recette/database/url
      property: url
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-credentials
  namespace: {{ .Values.common.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: smtp-credentials
  data:
  - secretKey: username
    remoteRef:
      key: kv/data/rdv-solidarites/recette/smtp/credentials
      property: username
  - secretKey: password
    remoteRef:
      key: kv/data/rdv-solidarites/recette/smtp/credentials
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: csp-report-uri
  namespace: {{ .Values.common.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: csp-report-uri
  data:
  - secretKey: csp-report-uri
    remoteRef:
      key: kv/data/rdv-solidarites/recette/csp_report_uri
      property: csp_report_uri
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sms-credentials
  namespace: {{ .Values.common.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sms-credentials
  data:
  - secretKey: default_provider_key
    remoteRef:
      key: kv/data/rdv-solidarites/recette/sms/credentials
      property: default_provider_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: franceconnect-credentials
  namespace: {{ .Values.common.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: franceconnect-credentials
  data:
  - secretKey: app_id
    remoteRef:
      key: kv/data/rdv-solidarites/recette/franceconnect/credentials
      property: app_id
   - secretKey: app_secret
    remoteRef:
      key: kv/data/rdv-solidarites/recette/franceconnect/credentials
      property: app_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-credentials
  namespace: {{ .Values.common.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-credentials
  data:
  - secretKey: app_id
    remoteRef:
      key: kv/data/rdv-solidarites/recette/github/credentials
      property: app_id
   - secretKey: app_secret
    remoteRef:
      key: kv/data/rdv-solidarites/recette/github/credentials
      property: app_secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netsize-api
  namespace: {{ .Values.common.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: netsize-api
  data:
  - secretKey: netsize_api_userpwd
    remoteRef:
      key: kv/data/rdv-solidarites/recette/netsize/api
      property: netsize_api_userpwd
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: places-credentials
  namespace: {{ .Values.common.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: places-credentials
  data:
  - secretKey: api_key
    remoteRef:
      key: kv/data/rdv-solidarites/recette/places/credentials
      property: api_key
  - secretKey: app_id
    remoteRef:
      key: kv/data/rdv-solidarites/recette/places/credentials
      property: app_id
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-key-base
  namespace: {{ .Values.common.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: secret-key-base
  data:
  - secretKey: secret_key_base
    remoteRef:
      key: kv/data/rdv-solidarites/recette/secret_key_base
      property: secret_key_base
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sendibule-credentials
  namespace: {{ .Values.common.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sendibule-credentials
  data:
  - secretKey: inbound_password
    remoteRef:
      key: kv/data/rdv-solidarites/recette/sendibule/credentials
      property: inbound_password
  - secretKey: password
    remoteRef:
      key: kv/data/rdv-solidarites/recette/sendibule/credentials
      property: password
  - secretKey: sms_api_key
    remoteRef:
      key: kv/data/rdv-solidarites/recette/sendibule/credentials
      property: sms_api_key
  - secretKey: username
    remoteRef:
      key: kv/data/rdv-solidarites/recette/sendibule/credentials
      property: username
  - secretKey: dsn_rails
    remoteRef:
      key: kv/data/rdv-solidarites/recette/sendibule/credentials
      property: dsn_rails
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: skylight-authentication
  namespace: {{ .Values.common.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: skylight-authentication
  data:
  - secretKey: skylight_authentication
    remoteRef:
      key: kv/data/rdv-solidarites/recette/skylight_authentication
      property: skylight_authentication