---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: webapp
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/instance: webapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
        app.kubernetes.io/instance: webapp
    spec:
      imagePullSecrets:
      - name: docker-regcred
      containers:
        - name: webapp
          image: "{{ .Values.image.repository }}/webapp:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: ALTERNATE_SMTP_ADDRESS
              value: {{ .Values.smtp.address | quote }}
            - name: ALTERNATE_SMTP_AUTHENTIFICATION
              value: {{ .Values.smtp.authentification | quote }}
            - name: ALTERNATE_SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            - name: ALTERNATE_SMTP_USERNAME
              value: {{ .Values.smtp.username | quote }}
              # valueFrom:
              #   secretKeyRef:
              #     name: alternate_smtp
              #     key: username
            - name: ALTERNATE_SMTP_PASSWORD
              value: {{ .Values.smtp.password | quote }}
              # valueFrom:
              #   secretKeyRef:
              #     name: alternate_smtp
              #     key: password
            - name: CSP_REPORT_URI
              value: {{ .Values.csp_report_uri | quote }}
            - name: DATABASE_URL
              value: {{ .Values.database.url | quote }}
            - name: DEFAULT_SMS_PROVIDER
              value: {{ .Values.sms.default_provider | quote }}
            - name: DEFAULT_SMS_PROVIDER_KEY
              value: {{ .Values.sms.default_provider_key | quote }}
            - name: DEPLOY_TASKS
              value: {{ .Values.deploy_tasks | quote }}
            - name: FORCE_SMS_PROVIDER
              value: {{ .Values.sms.force_provider | quote }}
            - name: FRANCECONNECT_APP_ID
              value: {{ .Values.franceconnect.app_id | quote }}
            - name: FRANCECONNECT_APP_SECRET
              value: {{ .Values.franceconnect.app_secret | quote }}
            - name: FRANCECONNECT_DISABLED
              value: {{ .Values.franceconnect.disabled | quote }}
            - name: FRANCECONNECT_HOST
              value: {{ .Values.franceconnect.host | quote }}
            - name: GITHUB_APP_ID
              value: {{ .Values.github.app_id | quote }}
            - name: GITHUB_APP_SECRET
              value: {{ .Values.github.app_secret | quote }}
            - name: HOST
              value: {{ .Values.host | quote }}
            - name: MAINTENANCE_PAGE_URL
              value: {{ .Values.maintenance_page_url | quote }}
            - name: MATOMO_APP_ID
              value: {{ .Values.matomo_app_ip | quote }}
            - name: NETSIZE_API_USERPWD
              value: {{ .Values.netsize_api_userpwd | quote }}
            - name: NO_VHOST
              value: {{ .Values.no_vhost | quote }}
            - name: PLACES_API_KEY
              value: {{ .Values.places.api_key | quote }}
            - name: PLACES_APP_ID
              value: {{ .Values.places.app_id | quote }}
            - name: RACK_ENV
              value: {{ .Values.rack.env | quote }}
            - name: RAILS_ENV
              value: {{ .Values.rails.env | quote }}
            - name: RAILS_LOG_TO_STDOUT
              value: {{ .Values.rails.log_to_stdout | quote }}
            - name: RAILS_SERVE_STATIC_FILES
              value: {{ .Values.rails.serve_static_files | quote }}
            - name: RDV_SOLIDARITES_INSTANCE_NAME
              value: {{ .Values.rdv_solidarites_instance_name | quote }}
            - name: REDIS_URL
              value: {{ .Values.redis_url | quote }}
            - name: SECRET_KEY_BASE
              value: {{ .Values.secret_key_base | quote }}
            - name: SENDINBLUE_INBOUND_PASSWORD
              value: {{ .Values.sendibule.inbound_password | quote }}
            - name: SENDINBLUE_PASSWORD
              value: {{ .Values.sendibule.password | quote }}
            - name: SENDINBLUE_SMS_API_KEY
              value: {{ .Values.sendibule.sms_api_key | quote }}
            - name: SENDINBLUE_USERNAME
              value: {{ .Values.sendibule.username | quote }}
            - name: SENTRY_DSN_RAILS
              value: {{ .Values.sendibule.dsn_rails | quote }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentry_environment | quote }}
            - name: SIGN_IN_AS_ALLOWED
              value: {{ .Values.sign_in_as_allowed | quote }}
            - name: SKYLIGHT_AUTHENTICATION
              value: {{ .Values.skylight_authentication | quote }}
            - name: DOMAIN_NAME
              value: {{ .Values.domain_name | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.rails.log_level | quote }}
          ports:
            - name: {{ .Values.webapp.port.name }}
              containerPort: {{ .Values.webapp.port.containerPort }}
              protocol: {{ .Values.webapp.port.protocol }}
          # livenessProbe:
          #   httpGet:
          #     path: {{ .Values.webapp.port.path }}
          #     port: {{ .Values.webapp.port.containerPort }}
          #   initialDelaySeconds: {{ .Values.webapp.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.webapp.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.webapp.port.path }}
              port: {{ .Values.webapp.port.containerPort }}
            initialDelaySeconds: {{ .Values.webapp.initialDelaySeconds }}
            periodSeconds: {{ .Values.webapp.periodSeconds }}
          resources:
            requests:
              cpu: {{ .Values.webapp.resources.requests.cpu }}
              memory: {{ .Values.webapp.resources.requests.memory }}
            limits:
              cpu: {{ .Values.webapp.resources.limits.cpu }}
              memory: {{ .Values.webapp.resources.limits.memory }}