---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: {{ .Values.common.namespace }}
  labels:
    app.kubernetes.io/name: webapp
    app.kubernetes.io/instance: webapp
spec:
  replicas: {{ .Values.webapp.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      app.kubernetes.io/instance: webapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
        app.kubernetes.io/instance: webapp
    spec:
      imagePullSecrets:
      - name: docker-regcred
      containers:
        - name: webapp
          image: "{{ .Values.image.repository }}/webapp:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: ALTERNATE_SMTP_ADDRESS
              value: {{ .Values.smtp.address | quote }}
            - name: ALTERNATE_SMTP_AUTHENTIFICATION
              value: {{ .Values.smtp.authentification | quote }}
            - name: ALTERNATE_SMTP_PORT
              value: {{ .Values.smtp.port | quote }}
            - name: ALTERNATE_SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: username
            - name: ALTERNATE_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: password
            - name: CSP_REPORT_URI
              valueFrom:
                secretKeyRef:
                  name: csp-report-uri
                  key: csp_report_uri
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-url
                  key: url
            - name: DEFAULT_SMS_PROVIDER
              value: {{ .Values.sms.default_provider | quote }}
            - name: DEFAULT_SMS_PROVIDER_KEY
              valueFrom:
                secretKeyRef:
                  name: sms-credentials
                  key: default_provider_key
            - name: DEPLOY_TASKS
              value: {{ .Values.deploy_tasks | quote }}
            - name: FORCE_SMS_PROVIDER
              value: {{ .Values.sms.force_provider | quote }}
            - name: FRANCECONNECT_APP_ID
              valueFrom:
                secretKeyRef:
                  name: franceconnect-credentials
                  key: app_id
            - name: FRANCECONNECT_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: franceconnect-credentials
                  key: app_secret
            - name: FRANCECONNECT_DISABLED
              value: {{ .Values.franceconnect.disabled | quote }}
            - name: FRANCECONNECT_HOST
              value: {{ .Values.franceconnect.host | quote }}
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: app_id
            - name: GITHUB_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: app_secret
            - name: HOST
              value: {{ .Values.host | quote }}
            - name: MAINTENANCE_PAGE_URL
              value: {{ .Values.maintenance_page_url | quote }}
            - name: MATOMO_APP_ID
              value: {{ .Values.matomo_app_ip | quote }}
            - name: NETSIZE_API_USERPWD
              valueFrom:
                secretKeyRef:
                  name: netsize-api
                  key: netsize_api_userpwd
            - name: NO_VHOST
              value: {{ .Values.no_vhost | quote }}
            - name: PLACES_API_KEY
              valueFrom:
                secretKeyRef:
                  name: places-credentials
                  key: api_key
            - name: PLACES_APP_ID
              valueFrom:
                secretKeyRef:
                  name: places-credentials
                  key: app_id
            - name: RACK_ENV
              value: {{ .Values.rack.env | quote }}
            - name: RAILS_ENV
              value: {{ .Values.rails.env | quote }}
            - name: RAILS_LOG_TO_STDOUT
              value: {{ .Values.rails.log_to_stdout | quote }}
            - name: RAILS_SERVE_STATIC_FILES
              value: {{ .Values.rails.serve_static_files | quote }}
            - name: RDV_SOLIDARITES_INSTANCE_NAME
              value: {{ .Values.rdv_solidarites_instance_name | quote }}
            - name: REDIS_URL
              value: {{ .Values.redis_url | quote }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secret-key-base
                  key: secret_key_base
            - name: SENDINBLUE_INBOUND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sendibule-credentials
                  key: inbound_password
            - name: SENDINBLUE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sendibule-credentials
                  key: password
            - name: SENDINBLUE_SMS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sendibule-credentials
                  key: sms_api_key
            - name: SENDINBLUE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sendibule-credentials
                  key: username
            - name: SENTRY_DSN_RAILS
              valueFrom:
                secretKeyRef:
                  name: sendibule-credentials
                  key: dsn_rails
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentry_environment | quote }}
            - name: SIGN_IN_AS_ALLOWED
              value: {{ .Values.sign_in_as_allowed | quote }}
            - name: SKYLIGHT_AUTHENTICATION
              valueFrom:
                secretKeyRef:
                  name: skylight-authentication
                  key: skylight_authentication
            - name: DOMAIN_NAME
              value: {{ .Values.domain_name | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.rails.log_level | quote }}
          ports:
            - name: {{ .Values.webapp.port.name }}
              containerPort: {{ .Values.webapp.port.containerPort }}
              protocol: {{ .Values.webapp.port.protocol }}
          # livenessProbe:
          #   httpGet:
          #     path: {{ .Values.webapp.port.path }}
          #     port: {{ .Values.webapp.port.containerPort }}
          #   initialDelaySeconds: {{ .Values.webapp.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.webapp.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.webapp.port.path }}
              port: {{ .Values.webapp.port.containerPort }}
            initialDelaySeconds: {{ .Values.webapp.initialDelaySeconds }}
            periodSeconds: {{ .Values.webapp.periodSeconds }}
          resources:
            requests:
              cpu: {{ .Values.webapp.resources.requests.cpu }}
              memory: {{ .Values.webapp.resources.requests.memory }}
            limits:
              cpu: {{ .Values.webapp.resources.limits.cpu }}
              memory: {{ .Values.webapp.resources.limits.memory }}