#Test change
name: Push docker image from pull request
on: [pull_request]
# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME}}
  WEBAPP_DOCKERFILE: ./docker/web/Dockerfile
  JOB_DOCKERFILE: ./docker/job/Dockerfile
jobs:
  push-image:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version)
    environment: lapin-beta-gouv
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code

    - name: Extract prnumber name
      shell: bash
      run: echo "##[set-output name=prnumber;]$(echo $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH"))"
      id: extract_prnumber

    - name: Check prnumber Name
      run: echo }$DOCKER_REPO_NAME/webapp:${{ steps.extract_prnumber.outputs.prnumber }
    - name: docker login
      run: | # log into docker registry account
        docker login $DOCKER_REPO_NAME -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

    - name: Build the Webapp Docker image
      run: docker build . --file $WEBAPP_DOCKERFILE --tag $DOCKER_REPO_NAME/webapp:${{ steps.extract_prnumber.outputs.prnumber }}
    - name: Docker Push Webapp image
      run: docker push $DOCKER_REPO_NAME/webapp:${{ steps.extract_prnumber.outputs.prnumber }}
    - name: Build the Job Docker image
      run: docker build . --file $JOB_DOCKERFILE --tag $DOCKER_REPO_NAME/jobs:${{ steps.extract_prnumber.outputs.prnumber }}
    - name: Docker Push Job image
      run: docker push $DOCKER_REPO_NAME/jobs:${{ steps.extract_prnumber.outputs.prnumber }}

